function [ success, baseVal ] = is_neumann_cluster(data, x, y, disc)
    baseVal = s_of(filter_cell(data,x,y));
    success = true;
    if baseVal > 0
        if    (((s_of(filter_cell(data,x,y+1)) < ((1-disc) * baseVal)) || ...
              (s_of(filter_cell(data,x,y+1)) > ((1+disc) * baseVal))))    ...
           || (((s_of(filter_cell(data,x,y-1)) < ((1-disc) * baseVal)) || ...
              (s_of(filter_cell(data,x,y-1)) > ((1+disc) * baseVal))))    ...
           || (((s_of(filter_cell(data,x+1,y)) < ((1-disc) * baseVal)) || ...
              (s_of(filter_cell(data,x+1,y)) > ((1+disc) * baseVal))))    ...
           || (((s_of(filter_cell(data,x-1,y)) < ((1-disc) * baseVal)) || ...
              (s_of(filter_cell(data,x-1,y)) > ((1+disc) * baseVal))))
            success = false;
        end
    else
        success = false;
    end
end